---
# tasks file for roles/Newrelic

- set_fact:
    flag: false

- name: Download Newrelic agent tar file
  get_url:
    url="http://download.newrelic.com/infrastructure_agent/binaries/linux/amd64/newrelic-infra_linux_{{ nrinfragent_version }}_amd64.tar.gz"
    dest="/opt/newrelic-infra_linux_{{ nrinfragent_version }}_amd64.tar.gz"
  register: output

- set_fact: flag="{{output.failed}}"

- debug:
    msg: "Download is failed"
  when: flag

- name: untar Newrelic package
  unarchive:
    src: /opt/newrelic-infra_linux_{{ nrinfragent_version }}_amd64.tar.gz
    dest: /opt
    mode: 0777
    remote_src: yes
  register: output1
  when: not flag

- set_fact: flag="{{output1.failed}}"

- debug:
    msg: "Untar is failed"
  when: flag

- name: Go to the folder and execute command
  command: chdir=/opt/newrelic-infra ./installer.sh
  become: yes

- name: Modify newrelic-infra.yml file
  lineinfile:
    path: /etc/newrelic-infra.yml
    state: present
    regexp: 'license_key:'
    line: "license_key:{{nrinfragent_license_key}}"
  become: yes
  register: output2
  when: not flag
  notify: restart newrelic-infra

- set_fact: flag="{{output2.failed}}"

- debug:
    msg: "Config. is failed"
  when: flag
